Bump cython, numpy
pypr/compyle pull request #105
Opened 2024-08-18 11:04 UTC by nauaneed

2024-08-18 11:04 UTC, pep8speaks commented
Hello @nauaneed! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`compyle/tests/test_cython_generator.py`](https://github.com/pypr/compyle/blob/135fc7cd64a67d847ae3c85aabe7658ab68ddd0d/compyle/tests/test_cython_generator.py):

> [Line 501:80](https://github.com/pypr/compyle/blob/135fc7cd64a67d847ae3c85aabe7658ab68ddd0d/compyle/tests/test_cython_generator.py#L501): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2024-08-18 13:37 UTC, prabhuramachandran requested changes
Looks good, thanks! Can you please bump the Python version to at least 3.11 or 3.12 so the tests run on latest Python.

2024-09-20 21:12 UTC, nauaneed commented on compyle/types.py
> +    TYPES['long long'] = KnownType('long long')
This fixes tests failing on windows but not sure if this is a good fix. All keys in the `TYPES` dict do not contain spaces as they are meant to be used with `@annotate` decorator?

2024-09-20 21:17 UTC, nauaneed commented
One failing test on windows remaining: `test_ext_module.py::TestExtModule::test_that_multiple_writes_do_not_occur_for_same_source`

2024-09-26 03:25 UTC, prabhuramachandran approved these changes
LGTM, thanks! We should fix the multiple writes error by using a proper cross platform lock like fasteners. Will try to do that later.

2024-09-26 03:26 UTC, merged