Dev rt
pypr/compyle pull request #78
Opened 2021-05-12 11:37 UTC by aerorohit

1. Added linspace for compyle array. 
2. Removed unused import of compyle array.

2021-05-12 11:37 UTC, pep8speaks commented
Hello @aerorohit! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`compyle/array.py`](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py):

> [Line 374:1](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L374): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 374:80](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L374): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 375:21](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L375): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 377:11](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L377): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 386:51](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L386): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 389:17](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L389): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 396:1](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L396): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 401:26](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L401): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 405:5](https://github.com/pypr/compyle/blob/2f18a2a94dc31063e89a4efd8a4c005c3778a271/compyle/array.py#L405): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2021-09-22 13:09 UTC, prabhuramachandran commented
Thanks @aerorohit can you please update the message here on the PR to summarize all the key changes you have made?

2021-09-22 14:32 UTC, aerorohit commented
Functions added in array.py

- `linspace`
- `diff`
- `trapz`
- `where`
- comparison operators for an array object
- tests for above functions and `argsort`, `ones_like`, `minimum`, `sum`
- removed unnecessary import of cffi to support older versions of pycuda.

2021-09-25 17:36 UTC, prabhuramachandran requested changes
Please make the requested changes. Thanks.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        raise Exception("num should be an integer")
Please provide a more helpful message here.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        raise Exception('num should be greater than 0')
Same here.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +def nDiff(i, y, x, b, lb):
Can you change the function name to be consistent with the rest, i.e. use `lower_case_with_underscores`.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +            + str(a.__len__()))
Use `len(a)` and not `a.__len__()`.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +    if(a.__len__() < n+1):
Do not call private methods, use `len(a)`

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        len_ar = a.__len__()
Not sure why you are using this, `__len__` please remove all such occurrences.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        if not x.__len__() == (y.__len__()):
Here too!

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +    if backend == 'opencl' or backend == 'cuda' or backend == 'C':
What is this backend C?

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +    e = Elementwise(take_bool_elwise_an, backend=backend)
This should be cached right?  Each time `take_bool` is called it is going to create a fresh elementwise, you should use some form of memoization as done in many places in compyle.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +    e = Elementwise(where_annotated, backend=backend)
This should be memoized.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        diff_kernel = Elementwise(nDiff, backend=backend)
Memoization please.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +    e = Elementwise(func_annotated, backend=arr.backend)
Memoization

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +            e = Elementwise(add_elwise, backend=self.backend)
Again here.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/array.py
> +        raise Exception("num should be an integer")
Also a better exception, not a generic Exception.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/tests/test_array.py
> +    comp = [int(i) for i in x_np.__getattribute__(method)(5)]
Arghh,  never call these protected methods, use `getattr(x, method)`.

2021-09-25 17:36 UTC, prabhuramachandran commented on compyle/tests/test_array.py
> +    out = x.__getattribute__(method)(5)
Never call these in public, use `getattr(x, method)`.

2021-09-26 03:28 UTC, prabhuramachandran requested changes
A few more minor issues.

2021-09-26 03:28 UTC, prabhuramachandran commented on compyle/array.py
> +        if not len(x) == (len(y)):
Remove extra brackets around `(len(y))`.

2021-09-26 03:28 UTC, prabhuramachandran commented on compyle/array.py
> +    where_annotated = annotate(where_elwise)
Can't you use the annotate decorator for the `where_elwise`?

2021-09-26 11:53 UTC, prabhuramachandran approved these changes

2021-09-26 11:57 UTC, merged